### ISSUE TITLE
Game freezes when hitting some kind of building limits

### ISSUE THREAD

**Issue by Steinin** [caiiiycuk/play-dune#6]
I reached the final map for Atreides and built a lot of concrete slabs to spread out my base and protect against nukes. Now the game freezes when I try to build more structures. Completed structures ready to be placed can be placed (outline marker appears) but game freezes when a location is chosen and button is pressed to select that location. The game also freezes under the same conditions if instead of placing the structure, the construction menu is chosen and the build button of another structure is pressed.

**Comment by caiiiycuk** [comment]
Please send me you game cookie, then i can load your save game.
Thanks.

**Comment by caiiiycuk** [comment]
Fixed here http://epicport.com
