### ISSUE TITLE
harvesters stop returning to base

### ISSUE THREAD

**Issue by dmcoles** [caiiiycuk/play-dune#8]
after some period of time the harvesters fill up to 100% then just hang around and dont return to base.

This prevents any further harvesting and i have no way to proceed in the game.

**Comment by caiiiycuk** [comment]
Please send me your save game

2013/10/7 dmcoles notifications@github.com

> after some period of time the harvesters fill up to 100% then just hang
> around and dont return to base.
> 
> This prevents any further harvesting and i have no way to proceed in the
> game.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/caiiiycuk/play-dune/issues/8
> .

## 

ó Õ×ÁÖÅÎÉÅÍ, çÕÒØÑÎÏ× áÌÅËÓÁÎÄÒ

**Comment by dmcoles** [comment]
i did email you my save game but i didnt get any reply

**Comment by caiiiycuk** [comment]
Sorry about that, please send saves again. caiiiycuk@gmail.com

**Comment by dmcoles** [comment]
no problem, email sent
